In [5]:
#to get array value individually
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [9]:
a=np.array([[1,2],[3,4],[5,6]])
a[2,0]

5

In [10]:
a.ndim

2

In [17]:
a=np.array([[1,2,3],[3,5,6],[5,8,9],[4,0,0]], dtype=np.float64)
a.itemsize
a

array([[1., 2., 3.],
       [3., 5., 6.],
       [5., 8., 9.],
       [4., 0., 0.]])

In [18]:
a.itemsize

8

In [19]:
a.size

12

In [20]:
a.shape

(4, 3)

In [24]:
np.zeros((3,2))
np.ones((1,3))

array([[1., 1., 1.]])

In [28]:
m=range(5)
m=np.arange(5)
m

array([0, 1, 2, 3, 4])

In [37]:
np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [44]:
np.linspace(2,10,3)

array([ 2.,  6., 10.])

In [48]:
a.reshape(3,4)

array([[1., 2., 3., 3.],
       [5., 6., 5., 8.],
       [9., 4., 0., 0.]])

In [49]:
a.ravel()

array([1., 2., 3., 3., 5., 6., 5., 8., 9., 4., 0., 0.])

In [50]:
a

array([[1., 2., 3.],
       [3., 5., 6.],
       [5., 8., 9.],
       [4., 0., 0.]])

In [54]:
a.min()
a.max()
a.sum()
a.sum(axis=1)

array([ 6., 14., 22.,  4.])

In [55]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 2.23606798, 2.44948974],
       [2.23606798, 2.82842712, 3.        ],
       [2.        , 0.        , 0.        ]])

In [56]:
np.std(a)

2.7938424357067015

In [66]:
b = np.array([[1,2], [3,4], [5,6]])
c = np.array([[7,8], [8,9], [10,11]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [67]:
c

array([[ 7,  8],
       [ 8,  9],
       [10, 11]])

In [65]:
#To perform Mathematical operations
b+c

array([[ 8, 10],
       [11, 13],
       [15, 17]])

In [69]:
c-b

array([[6, 6],
       [5, 5],
       [5, 5]])

In [70]:
c*b

array([[ 7, 16],
       [24, 36],
       [50, 66]])

In [72]:
b/c

array([[0.14285714, 0.25      ],
       [0.375     , 0.44444444],
       [0.5       , 0.54545455]])

In [74]:
c.dot(b)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)